### ISSUE TITLE
about subselectfeatures

### ISSUE THREAD

**Issue by aremazeilles** [asiertecnalia/sarafun_process_experiments#10]
this is related to file sarafun_process_experiments/src/observation/frame_selection/subselectFeatures.m

I think it could be strongly simplified using the powerness of matlab / octave

basically you want to maintain only some rows.
if features contains the features you want to keep, then you just have to write:

for i=1:samples
  reduced_signals{i} = raw_dara{i}(features,:)
end

Thatś all folks

By the way, when you call it, you do not have to write:
features2keep =[1 2 3 blablabla 23 24]
This is enough:
features2keep = [1:24];

**Comment by irasines** [comment]
oki doki to the firs part! didn't know you could place a vector there :) 
In the second case, 
features2keep =[1 2 3 blablabla 23 24] ->features2keep = [1:24]; 
this just works (i think) when you wanna select all consecutive features, if you want the vector to be features2keep = [ 1 4 8] because you want to compare them, you have to write it down

**Comment by aremazeilles** [comment]
For [1 4 8] you are right, but you can still write the following:

xoctave:1> x = [1 2:5 8:9]
x =

   1   2   3   4   5   8   9

**Comment by irasines** [comment]
Yup, the new version for the function is up :)
